POST http://localhost:9999/banners.save HTTP/1.1

###
POST http://localhost:9999/banners.getAll HTTP/1.1

###
POST http://localhost:9999/banners.getByID?id=0 HTTP/1.1

###
POST http://localhost:9999/banners.removeByID?id=0 HTTP/1.1

